# Generated by Django 4.2.10 on 2024-03-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Информация пользователя', 'verbose_name_plural': 'Информация пользователей'},
        ),
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
