# Generated by Django 4.2.10 on 2024-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_infouser_options_alter_infouser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='infouser', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='job',
            field=models.CharField(default=1, max_length=255, verbose_name='Профессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(default=1, verbose_name='YOUTUBE'),
            preserve_default=False,
        ),
    ]
