# Generated by Django 4.2.10 on 2024-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_infouser_descriptions_infouser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='image',
            field=models.ImageField(upload_to='infouser_images', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефонный номер'),
        ),
    ]
