# Generated by Django 4.2.10 on 2024-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_infouser_image_alter_infouser_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name='Годы опыта')),
                ('project', models.IntegerField(verbose_name='Завершенные проекты')),
                ('clients', models.IntegerField(verbose_name='Доволные клиенты')),
            ],
            options={
                'verbose_name': 'Я в числе',
                'verbose_name_plural': 'Я в числах',
            },
        ),
    ]
