# Generated by Django 4.2.10 on 2024-03-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_nubers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nubers',
            new_name='Numbers',
        ),
    ]
